
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes  10;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  127.0.0.1;
          resolver kube-dns.kube-system.svc.cluster.local valid=5s;
          
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
          }

          location /dashboard {
            rewrite /dashboard/(.*) /$1  break;
            proxy_pass https://kubernetes-dashboard.kubernetes-dashboard:443/;
            proxy_set_header Host $host;
          }

          location /portainer {
            rewrite /portainer/(.*) /$1  break;
            proxy_pass http://portainer.portainer:9000/;
            proxy_set_header Host $host;
          }

        }
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-private
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        nodeRole: master
      containers:
        - name: nginx-container
          image: nginx:latest
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-private-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
